<project><modelVersion>4.0.0</modelVersion><groupId>a</groupId><artifactId>b</artifactId><version>1</version><dependencies><dependency><groupId>org.testng</groupId><artifactId>testng</artifactId><version>7.10.2</version></dependency><dependency><groupId>org.seleniumhq.selenium</groupId><artifactId>selenium-java</artifactId><version>4.25.0</version></dependency><dependency><groupId>com.epam.reportportal</groupId><artifactId>agent-java-testng</artifactId><version>5.4.0</version></dependency></dependencies></project>
