// Builds the browser-only HyperExecute Studio into web/dist/: index.html + app.css + app.js.
// app.js = the UI + the shared core (../src) bundled for the browser, Node built-ins swapped for the shims
// in src/shims (in-memory filesystem, fixed virtual home), minified and obfuscated.
//   npm run build        production (obfuscated)
//   npm run build:dev    readable, with a source map, for debugging

const fs = require("fs");
const path = require("path");
const esbuild = require("esbuild");

const dev = process.argv.includes("--dev");
const here = __dirname;
const out = path.join(here, "dist");
const shim = (f) => path.join(here, "src", "shims", f);

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

const version = JSON.parse(fs.readFileSync(path.join(here, "package.json"), "utf8")).version;

// Sample repos for "Try a sample" on the landing page, embedded from the test fixtures (text files only).
const SAMPLES = { "maven-testng": "Maven + TestNG", "playwright-projects": "Playwright" };
const sampleData = {};
for (const [dir, label] of Object.entries(SAMPLES)) {
  const files = {};
  (function walk(abs, rel) {
    for (const e of fs.readdirSync(abs, { withFileTypes: true })) {
      if (["target", "node_modules", ".gradle", "build"].includes(e.name)) continue;
      const r = rel ? rel + "/" + e.name : e.name;
      if (e.isDirectory()) walk(path.join(abs, e.name), r);
      else if (!/\.(class|jar|lock)$/.test(e.name)) files[r] = fs.readFileSync(path.join(abs, e.name), "utf8");
    }
  })(path.join(here, "..", "test", "fixtures", dir), "");
  sampleData[dir === "maven-testng" ? "checkout-tests" : "web-e2e"] = { label, files };
}
fs.writeFileSync(path.join(here, "src", "samples.gen.js"), "// generated by build.js from test/fixtures — do not edit\nexport const SAMPLES = " + JSON.stringify(sampleData) + ";\n");

esbuild.buildSync({
  entryPoints: [path.join(here, "src", "app.js")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["chrome110", "firefox115", "safari16"],
  outfile: path.join(out, "app.js"),
  minify: !dev,
  sourcemap: dev,
  legalComments: "none",
  logLevel: "warning",
  alias: {
    "node:fs": shim("fs.js"), fs: shim("fs.js"),
    "node:os": shim("os.js"), os: shim("os.js"),
    "node:url": shim("url.js"), url: shim("url.js"),
    "node:path": require.resolve("path-browserify"), path: require.resolve("path-browserify"),
    // one copy of yaml for the whole bundle, from web/ (Netlify installs only this folder)
    yaml: path.dirname(require.resolve("yaml/package.json")),
  },
  inject: [shim("process.js")],
  define: { __STUDIO_VERSION__: JSON.stringify(version) },
  nodePaths: [path.join(here, "node_modules"), path.join(here, "..", "node_modules")],
});

if (!dev) {
  const Obfuscator = require("javascript-obfuscator");
  const code = fs.readFileSync(path.join(out, "app.js"), "utf8");
  const r = Obfuscator.obfuscate(code, {
    target: "browser",
    compact: true,
    identifierNamesGenerator: "hexadecimal",
    renameGlobals: false,
    stringArray: true,
    stringArrayEncoding: ["base64"],
    stringArrayThreshold: 0.75,
    stringArrayRotate: true,
    stringArrayShuffle: true,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    selfDefending: false,
    transformObjectKeys: false,
    unicodeEscapeSequence: false,
  });
  fs.writeFileSync(path.join(out, "app.js"), r.getObfuscatedCode());
}

esbuild.buildSync({ entryPoints: [path.join(here, "src", "app.css")], minify: !dev, outfile: path.join(out, "app.css"), logLevel: "warning" });
// cache-busting query so a new deploy is picked up
const html = fs.readFileSync(path.join(here, "src", "index.html"), "utf8").replace(/__V__/g, version + (dev ? "-dev" : ""));
fs.writeFileSync(path.join(out, "index.html"), html);
fs.copyFileSync(path.join(here, "src", "icon.svg"), path.join(out, "icon.svg"));
// self-hosted fonts: no third-party font CDN, so the page still only talks to LambdaTest (and Anthropic if the visitor opts in)
fs.mkdirSync(path.join(out, "fonts"), { recursive: true });
fs.copyFileSync(require.resolve("@fontsource-variable/inter/files/inter-latin-wght-normal.woff2"), path.join(out, "fonts", "inter.woff2"));
fs.copyFileSync(require.resolve("@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2"), path.join(out, "fonts", "jetbrains-mono.woff2"));
console.log(`web/dist built (${dev ? "dev" : "production"}): ${fs.readdirSync(out).filter((f) => fs.statSync(path.join(out, f)).isFile()).map((f) => `${f} ${(fs.statSync(path.join(out, f)).size / 1024).toFixed(0)} KB`).join(", ")}`);
